server:
  port: 3051

spring:
  application:
    name: wholesale-mall
  output:
    ansi:
      enabled: always
  datasource:
   name: test
   type: com.zaxxer.hikari.HikariDataSource
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://172.16.10.196:3306/wholesale_mall?useSSL=false
   username: root
   password: root
#   schema: classpath:initialization/schema.sql  # 此操作会导致重启时重新初始化数据库，慎用！
   hikari:
     connection-init-sql: set names utf8mb4;
# mq链接配置
  rabbitmq:
    host: ${RABBIT_MQ_HOST:172.16.10.196}
    port: ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

wholesale-mall:
  id-generator:
    worker-id: 1
    data-center-id: 1
  rest-template:
    string-http-message-converter-default-charset: UTF-8
  payment:
    charset: UTF-8
    send-sms:
      url: http://dev.food-see.com/3rd-party-services/sms-captcha/{0}/{1}/sms
#      version: v1-5-0
    validate-sms:
      url: http://dev.food-see.com/3rd-party-services/sms-captcha/{0}/{1}/sms/validate
#      version: v1-5-0
#    send-message-url: http://172.16.10.196:5111/sms-captcha/{0}/{1}/sms
#    validate-message-url: http://172.16.10.196:5111/sms-captcha/{0}/{1}/sms/validate
    we-chat-oauth:
      app-id: wx03256e1fd0575796
      app-secret: 09db900868f565e4e65ee36eb4f87f3a
      app-redirect-uri: https://onlinetest.food-see.com/user/wechat/authorize
      app-front-uri: https://onlinetest.food-see.com/weixin/
    we-chat-pay:
      partner-id: 1497940112
      partner-key: aZ2J68OrUnvkNtTdSasGLBnGRjceHRS2
      pkcs12: classpath:apiclient_cert.p12
      timeout-express: 6
      recharge-notify-url: https://onlinetest.food-see.com/wechat/recharge/notify
      order-notify-url: https://onlinetest.food-see.com/wechat/order/notify
      invoice-notify-url: https://onlinetest.food-see.com/wechat/invoice/notify
      order-offline-notify-url: https://onlinetest.food-see.com/wechat/offline/notify
      payunit: 100
      proxy: nonginx
  rabbitmq:
    direct-queue:
      order-create:
#延迟队列信道
        direct_exchange_name: order-direct-exchange
#延迟队列队列名
        dlx_queue_name: order-dlx-queue
#转发队列队列名
        repeat_queue_name: order-repeat-queue
      pay-create:
#延迟队列信道
        direct_exchange_name: pay-direct-exchange
#延迟队列队列名
        dlx_queue_name: pay-dlx-queue
#转发队列队列名
        repeat_queue_name: pay-repeat-queue
    fanout-queue:
#订单创建广播
      order-created-event:
        - order-create-publisher
#订单支付成功广播
      order-paid-event:
        - coupon-publisher
        - flasesale-publisher
      order-payed-event:
        - test-publisher-1
        - test-publisher-4
      store-check-event:
        - add-coupon
#收货人代码
  inventory:
    receiver_code: "00889"
hd:
  config:
    charset: UTF-8
    username: test01
    password: AePq88kJbleNGUDT
    operator: user
    url: http://api.sandbox.u.hd123.com/
    shop-id: 0418
    platform-id: qianfan
    platform-name: 千帆
    tenant-id: test01
    hd-card: http://172.16.10.108:8180/hdcard-services/api
    authentication-username: guest
    authentication-password: guest
    h4rest: http://172.16.10.109:7280/h4rest-server/rest/h5rest-server/core/

microx:
  swagger:
    title: 水果熟了 - 批发商城
    description: 批发商城 - 接口列表
    version: 20180416
  probe:
    exception-monitor:
      stack-trace-package-prefix: "com.lhiot**, com.sgsl**, com.leon**"
  redisson:
    server-mode: single
    addresses: ${REDISSON_HOST:172.16.10.195}:${REDISSON_PORT:6379}

logging:
  file: ./logs/${spring.application.name}.log
  level:
    root: debug
    org.apache: warn
    org.hibernate: warn
    org.springframework: warn
    org.springframework.boot.actuate.endpoint: info
    org.springframework.cloud.bus.event: debug
    springfox.documentation: warn
    org.mybatis.spring: warn
    javax.activation: warn
    com.sun.jersey: warn
    org.redisson: warn
    com.netflix: warn
    com.zaxxer: warn
    org.I0Itec: warn
    io.netty: warn
    com.sun: warn
    javax: warn
    sun: warn
    rx: warn
