server:
  port: 3051

spring:
  application:
    name: wholesale-mall
  output:
    ansi:
      enabled: always
  datasource:
   name: test
   type: com.zaxxer.hikari.HikariDataSource
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://172.16.10.196:3306/leon_test?useSSL=false
   username: root
   password: root
   schema: classpath:initialization/schema.sql  # 此操作会导致重启时重新初始化数据库，慎用！
   hikari:
     connection-init-sql: set names utf8mb4;

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

wholesale-mall:
  id-generator:
    worker-id: 1
    data-center-id: 1

microx:
  swagger:
    title: 水果熟了 - 批发商城
    description: 批发商城 - 接口列表
    version: 20180416

logging:
  file: ./logs/${spring.application.name}.log
  level:
    root: debug
    org.apache: warn
    org.hibernate: warn
    org.springframework: warn
    org.springframework.boot.actuate.endpoint: info
    org.springframework.cloud.bus.event: debug
    springfox.documentation: warn
    org.mybatis.spring: warn
    javax.activation: warn
    com.sun.jersey: warn
    org.redisson: warn
    com.netflix: warn
    com.zaxxer: warn
    org.I0Itec: warn
    io.netty: warn
    com.sun: warn
    javax: warn
    sun: warn
    rx: warn