server:
  port: 3051

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.196:3306/leon_test?useSSL=false
    username: root
    password: root
    hikari:
      connection-init-sql: set names utf8mb4;
      maximum-pool-size: 8
      max-lifetime: 60000
      minimum-idle: 4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    expiration: 4500
  redis:
    host: 172.16.10.195