server:
  port: 3051

spring:
  application:
    name: wholesale-mall
  output:
    ansi:
      enabled: always
  datasource:
   name: test
   type: com.zaxxer.hikari.HikariDataSource
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://172.16.10.196:3306/wholesale_mall?useSSL=false
   username: root
   password: root
   schema: classpath:initialization/schema.sql  # 此操作会导致重启时重新初始化数据库，慎用！
   hikari:
     connection-init-sql: set names utf8mb4;

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

wholesale-mall:
  id-generator:
    worker-id: 1
    data-center-id: 1

food-see:
  payment:
    charset: UTF-8
    we-chat-oauth:
      app-id: wx8521acbe400f89e3
      app-secret: 5176ebed12516da3cabb3a4d0e6d3ad6
      app-redirect-uri: https://online.food-see.com/wholesale-mall/user/weixin/authorize
    we-chat-pay:
      partner-id: 1497940112
      partner-key: aZ2J68OrUnvkNtTdSasGLBnGRjceHRS2
      pkcs12: classpath:apiclient_cert.p12
      timeout-express: 6
      recharge-notify-url: https://online.food-see.com/wholesale-mall/wechat/recharge/notify
      order-notify-url: https://online.food-see.com/wholesale-mall/wechat/order/notify
      payunit: 100
      proxy: nonginx
hd:
  config:
    charset: UTF-8
    username: test01
    password: AePq88kJbleNGUDT
    operator: user
    url: http://api.sandbox.u.hd123.com/
    shop-id: 0418
    platform-id: qianfan
    platform-name: 千帆
    tenant-id: test01
    hd-card: http://172.16.10.108:8180/hdcard-services/api
    authentication-username: guest
    authentication-password: guest
    h4rest: http://172.16.10.109:7280/h4rest-server/rest/h5rest-server/core/

microx:
  swagger:
    title: 水果熟了 - 批发商城
    description: 批发商城 - 接口列表
    version: 20180416

logging:
  file: ./logs/${spring.application.name}.log
  level:
    root: debug
    org.apache: warn
    org.hibernate: warn
    org.springframework: warn
    org.springframework.boot.actuate.endpoint: info
    org.springframework.cloud.bus.event: debug
    springfox.documentation: warn
    org.mybatis.spring: warn
    javax.activation: warn
    com.sun.jersey: warn
    org.redisson: warn
    com.netflix: warn
    com.zaxxer: warn
    org.I0Itec: warn
    io.netty: warn
    com.sun: warn
    javax: warn
    sun: warn
    rx: warn

